spring:
  profiles:
    active: prd
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://projectmanager:KrbDyw22XzqLbmZE@freespin.yolwbdu.mongodb.net/?retryWrites=true&w=majority
      database: sgi-user-prd